In [19]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [31]:
df = pd.read_csv('/Users/chengyinliu/Desktop/PCA.dat', header = None)
df_new = pd.read_csv('/Users/chengyinliu/D/2019_Spring/DSO562_Fraud Analytics/ASSIGNMENTS/WEEK_2/NY property data.csv')

In [32]:
BBLE = df_new['BBLE']

In [33]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.275429,-0.251655,-0.408204,0.314377,1.168940,0.304470,-0.129236,0.605491,-0.319156,-0.883406,-2.095610,-0.823422,0.687967,3.831450,-0.741218,-1.973755
1,0.699177,-0.907691,7.270555,3.254374,8.942633,-7.638284,2.125981,2.699764,3.721602,0.593581,8.651564,1.115782,6.139868,-4.596712,-3.455148,2.348442
2,-0.001459,-0.014881,0.094918,0.038615,-0.015218,0.043801,-0.067558,0.012459,0.105356,-0.007679,0.155758,-0.011332,0.179413,0.303611,-0.243014,0.011718
3,0.037838,-0.038835,-0.027698,-0.024951,0.044644,0.027380,-0.151486,0.074440,0.125506,-0.178669,-0.246203,-0.471486,0.297836,0.722995,-0.451401,-0.233063
4,5.889846,-3.506308,-1.507594,-12.177238,12.544221,-1.395918,-16.877855,13.099793,4.210799,-1.851879,1.388456,-7.977868,6.528517,4.633584,-8.288579,-0.308391

In [34]:
df_o = df.iloc[:,0:8]

In [35]:
df_o.head()

,0,1,2,3,4,5,6,7
0,0.275429,-0.251655,-0.408204,0.314377,1.168940,0.304470,-0.129236,0.605491
1,0.699177,-0.907691,7.270555,3.254374,8.942633,-7.638284,2.125981,2.699764
2,-0.001459,-0.014881,0.094918,0.038615,-0.015218,0.043801,-0.067558,0.012459
3,0.037838,-0.038835,-0.027698,-0.024951,0.044644,0.027380,-0.151486,0.074440
4,5.889846,-3.506308,-1.507594,-12.177238,12.544221,-1.395918,-16.877855,13.099793

In [36]:
df_n = df.iloc[:,8:]

In [37]:
df_n.head()

,8,9,10,11,12,13,14,15
0,-0.319156,-0.883406,-2.095610,-0.823422,0.687967,3.831450,-0.741218,-1.973755
1,3.721602,0.593581,8.651564,1.115782,6.139868,-4.596712,-3.455148,2.348442
2,0.105356,-0.007679,0.155758,-0.011332,0.179413,0.303611,-0.243014,0.011718
3,0.125506,-0.178669,-0.246203,-0.471486,0.297836,0.722995,-0.451401,-0.233063
4,4.210799,-1.851879,1.388456,-7.977868,6.528517,4.633584,-8.288579,-0.308391

In [38]:
a = df_n.values
b = df_o.values

In [39]:
df = pd.DataFrame(a - b)

In [40]:
df.head()

,0,1,2,3,4,5,6,7
0,-0.594584,-0.631751,-1.687406,-1.137799,-0.480973,3.526980,-0.611982,-2.579247
1,3.022424,1.501271,1.381009,-2.138592,-2.802765,3.041571,-5.581128,-0.351322
2,0.106815,0.007202,0.060839,-0.049948,0.194630,0.259810,-0.175456,-0.000741
3,0.087667,-0.139833,-0.218505,-0.446535,0.253192,0.695615,-0.299915,-0.307504
4,-1.679048,1.654430,2.896050,4.199370,-6.015704,6.029502,8.589277,-13.408184

In [41]:
df['sum'] = df.apply(np.sum, axis = 1)

In [42]:
df.head()

,0,1,2,3,4,5,6,7,sum
0,-0.594584,-0.631751,-1.687406,-1.137799,-0.480973,3.526980,-0.611982,-2.579247,-4.196762
1,3.022424,1.501271,1.381009,-2.138592,-2.802765,3.041571,-5.581128,-0.351322,-1.927531
2,0.106815,0.007202,0.060839,-0.049948,0.194630,0.259810,-0.175456,-0.000741,0.403151
3,0.087667,-0.139833,-0.218505,-0.446535,0.253192,0.695615,-0.299915,-0.307504,-0.375817
4,-1.679048,1.654430,2.896050,4.199370,-6.015704,6.029502,8.589277,-13.408184,2.265693

In [43]:
df["BBLE"] = BBLE

In [44]:
df.head()

,0,1,2,3,4,5,6,7,sum,BBLE
0,-0.594584,-0.631751,-1.687406,-1.137799,-0.480973,3.526980,-0.611982,-2.579247,-4.196762,1000010101
1,3.022424,1.501271,1.381009,-2.138592,-2.802765,3.041571,-5.581128,-0.351322,-1.927531,1000010201
2,0.106815,0.007202,0.060839,-0.049948,0.194630,0.259810,-0.175456,-0.000741,0.403151,1000020001
3,0.087667,-0.139833,-0.218505,-0.446535,0.253192,0.695615,-0.299915,-0.307504,-0.375817,1000020023
4,-1.679048,1.654430,2.896050,4.199370,-6.015704,6.029502,8.589277,-13.408184,2.265693,1000030001

In [49]:
df.sort_values('sum', ascending = False)

,0,1,2,3,4,5,6,7,sum,BBLE
585117,-128.216521,164.178276,270.800289,-603.922998,19.935149,102.944907,405.001883,151.086611,381.807597,4004200001
565397,-289.773900,282.978526,167.404095,102.733559,222.009331,60.483481,-137.079612,-63.312595,345.442885,3085910100
293329,-75.405939,61.756459,24.940110,181.209551,-144.011251,-35.602644,45.137221,234.440299,292.463806,3011170001
398250,-52.017296,43.205349,18.482445,129.379047,-118.240126,-3.804096,31.861469,213.008335,261.875127,3044520002
248664,-40.797750,49.904495,53.010898,-45.931920,-58.013963,-18.107359,-47.492096,350.963535,243.535840,2056500001
585119,-80.652686,102.813675,169.789256,-375.075861,12.416341,63.579999,254.443536,93.986889,241.301149,4004200101
245572,-26.234678,23.727115,12.207761,68.540405,-80.637687,-3.932751,18.413160,164.053155,176.136480,2055830100
918203,-120.895338,107.765238,97.128802,5.257878,-75.165689,32.454994,104.147771,0.546116,151.239772,4151000700
501142,-30.622682,25.982971,11.924417,76.157195,-63.483766,-5.666672,16.484651,111.479037,142.255151,3069440165
642966,-32.365934,23.768116,14.904566,67.321771,-91.538579,1.592465,58.211570,84.019738,125.913714,4022800001
886633,-27.791296,23.331044,10.823832,27.355424,-58.813265,-1.580311,-10.258791,155.953759,119.020397,4124060122
85885,-117.432577,70.326597,41.502371,246.716553,-261.987761,33.085114,335.470381,-231.058587,116.622092,1012540010
985596,-15.524738,14.249634,4.675931,43.077012,-55.100156,-3.132360,9.155988,111.293330,108.694640,5023590001
771993,-25.114147,18.759120,11.683588,51.591590,-72.446461,1.279651,43.390935,69.706340,98.850617,4077230010
992603,-27.582125,23.451784,9.205040,19.103155,-42.441634,2.559904,-4.451750,116.414136,96.258510,5026650020
964933,-32.240416,27.215381,15.288790,77.037028,-49.958155,-29.439915,9.614216,75.132219,92.649150,5009020001
771988,-23.665198,20.126903,17.036282,-12.839898,-46.799247,5.885886,21.120192,108.428711,89.293632,4077200100
134442,-8.368791,5.976812,7.648566,29.125037,-65.693899,0.136905,42.663624,75.013414,86.501668,1018970001
921879,-9.164076,7.198443,8.303589,23.271294,-51.851936,1.063509,28.661952,76.652759,84.135534,4156490300
177303,-10.184486,10.246333,6.494211,28.218809,-34.662684,0.555051,4.353711,77.427271,82.448216,2034630001
209711,-16.193514,15.230015,11.804175,40.357805,-28.680257,-26.628639,8.896541,77.272669,82.058795,2043350001
691873,-24.026273,20.502325,10.746321,61.593515,-35.706114,-28.432791,7.277436,69.073580,81.027998,4039071050
179210,-9.797884,9.919402,6.386508,27.257172,-33.551966,0.679252,4.009505,75.336969,80.238959,2035430001
297158,-16.769930,14.925990,7.036521,41.976159,-39.774888,0.127494,2.832226,68.090515,78.444086,3011830001
501164,-16.650092,17.175814,8.789165,3.370415,-18.698204,-6.017307,1.212080,87.033052,76.214925,3069460900
764311,-13.407460,10.508084,9.185663,30.050598,-48.429732,1.914173,24.741652,58.245035,72.808012,4072900001
720599,-11.529145,5.263537,-1.450114,23.761427,-54.678130,2.738179,25.594190,81.258980,70.958925,4051730006
665157,-13.653175,10.666645,9.194494,30.084548,-46.531148,2.443407,24.692477,53.869159,70.766408,4030720001
918204,-55.987533,50.944236,46.494040,-1.906713,-32.916906,17.610643,46.046406,0.160175,70.444348,4152000001
729561,-7.954680,6.742755,7.217838,20.721038,-41.221255,1.187224,18.049181,63.687195,68.429296,4055090430
...,...,...,...,...,...,...,...,...,...,...
7054,-0.748700,-1.060546,-0.824521,-11.884261,-23.369861,4.002279,-20.752029,-32.699943,-87.337582,1000580001E
33750,-5.259026,0.613256,8.945548,-11.597193,-34.853166,-16.962255,-19.615157,-8.923556,-87.651549,1006940042
1066921,-12.948625,-6.821682,3.054439,-13.397209,-39.140232,-4.665012,-0.228448,-17.030309,-91.177077,5078000235
127152,-26.964793,15.864990,11.889269,50.837033,-63.441227,4.427435,53.107240,-140.447739,-94.727793,1018020034
304353,-8.583145,-3.702675,-0.223382,-5.247062,-63.368527,-11.212490,-8.442135,3.237469,-97.541948,3013430016
304355,-9.731422,-3.971653,0.565402,-5.036895,-69.976233,-12.807708,-7.702232,10.193058,-98.467683,3013430025
330290,-13.762637,14.086229,18.418225,-9.039351,-57.610778,-27.878242,-52.767023,25.891730,-102.661846,3019190001
304342,-8.088593,-3.790850,-0.849837,-6.663500,-54.985983,-9.351344,-9.525326,-9.782666,-103.038098,3013430004
235454,-11.806705,8.058791,2.300722,-3.507248,-29.545734,-7.043883,-40.637729,-24.640575,-106.822362,2051410440
1070514,-14.079226,-4.449070,5.912942,-6.532856,-47.530006,-14.547992,-10.877233,-18.525623,-110.629064,5080370006
562741,-12.277718,-12.680650,3.800570,-2.721781,-33.400593,-4.345514,8.876966,-64.007478,-116.756197,3084950041
304343,-10.089437,-4.381913,0.675221,-7.278651,-68.775514,-13.035983,-8.443298,-8.828155,-120.157731,3013430005
638690,-60.583575,41.661789,33.021618,110.221778,-230.312387,-40.690201,12.378062,-6.331666,-140.634582,4020180001
794105,-12.462438,-1.565744,12.215178,-10.507970,-66.324805,-27.175377,-21.981653,-21.631793,-149.434603,4089460047
1070427,-16.342340,-6.946397,2.773170,-14.582612,-63.283542,-13.216098,-12.767138,-34.228531,-158.593488,5080340027
556608,-2.835850,13.167137,-124.753006,-28.402624,-29.649448,-58.469703,28.361105,37.672748,-164.909642,3083120001
797935,-9.973520,-3.586764,3.388034,-16.570221,-77.762984,-18.824557,-18.450557,-28.788069,-170.568637,4090550033
565391,-556.640909,566.901195,-240.069725,30.039753,306.979053,-47.486127,-148.416667,-85.262279,-173.955706,3085900700
821852,1.688221,9.274554,-119.795344,-38.008167,-14.164987,-48.812793,19.510692,9.347024,-180.960801,4098350040E
1067359,1.267611,13.458082,-213.693924,-72.531428,-88.633079,160.155104,-19.753418,8.822697,-210.908354,5078530085
794104,-14.997958,-1.810358,16.019858,-16.166265,-99.049918,-40.223155,-37.016396,-43.472344,-236.716535,4089460045
127321,-15.791054,8.273380,11.862772,26.845752,-101.433330,-23.863889,-13.546133,-148.993923,-256.646426,1018190010
1067000,-32.815345,-4.057037,29.000036,-40.947242,-130.368234,-52.050229,-48.358924,-33.667886,-313.264860,5078120132
920627,-17.127524,-9.977899,9.229238,-21.958696,-150.770378,-38.742733,-7.493268,-80.454690,-317.295948,4155770029
823223,-26.671666,5.534261,36.654965,-72.858468,-123.770213,-74.786013,-172.103177,36.369632,-391.630679,4098940047
935157,-68.141172,13.494733,80.401581,-191.336454,-115.487020,-92.411402,-265.488925,128.324265,-510.644394,5000130060
917941,-100.589795,108.455790,92.111240,-36.318987,-211.989695,-134.485557,-436.813946,111.233658,-608.397290,4142600001
776305,-9.978562,50.145729,-783.066184,-245.396497,-145.656553,-325.689555,189.963649,56.941386,-1212.736588,4080100001
632815,-715.624229,-733.715611,-14.763106,-46.995526,50.724258,-14.921413,0.439919,19.868992,-1454.986715,4018420001
585438,-66.650497,75.727314,157.833132,-307.589022,-469.447845,-198.640417,-280.144230,-405.269194,-1494.180759,4004590005

In [ ]:
from keras.models import Model
from keras.layers import Input, Dense

df = pd.read_csv("")

encoding_dim = 4
input_layer = Input(shape=(8,))
encoder = Dense(encoding_dim, activation='sigmoid')(input_layer)
decoder = Dense(8, activation='sigmoid')(encoder)
autoencoder = Model(input_layer, decoder)


autoencoder.compile(optimizer='adam',
                    loss='mean_squared_error')


autoencoder.fit(df, df,
                epochs=3,
                batch_size=32,
                shuffle=True)